apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: "{{ template "flyway.fullname" . }}"
  labels:
    {{- include "flyway.labels" . | nindent 4 }}
  namespace: demo
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backendType: vault
  dataFrom:
  - {{ .Values.secretPath }}
