apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ template "flyway.fullname" . }}"
  namespace: demo
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "2"
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: flyway
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args:
            - baseline
            - repair
            - migrate
            - info
          envFrom:
          - secretRef:
              name: "{{ include "flyway.fullname" . }}"
          env:
            - name: FLYWAY_LOCATIONS
              value: 'filesystem:/sql'
